- hosts: all
  tasks:
    - name: apply secret yaml
      shell: kubectl apply -f /tmp/app-secret.yaml
    - name: apply deployment yaml
      shell: kubectl apply -f /tmp/app-deployment.yaml
    - name: export IP port
      shell: sudo export IP=$(kubectl get po -o wide | tail -n 1 | awk '{print $6}')
    - name: curl
      shell: sudo curl <NODE_IP>:$NODE_PORT