- hosts: all
  become: true
  tasks:
    - name: docker build
      shell: sudo docker build -t username/deneme-app /tmp
    - name: docker login
      shell: sudo docker login -u="username" -p="passwd" docker.io
    - name: docker push
      shell: sudo docker push username/deneme-app:latest