- hosts: all
  become: true
  tasks:
    - name: docker build
      shell: sudo docker build -t ekininaal/deneme-app /tmp
    - name: docker login
      shell: sudo docker login -u="xxx" -p="xxx" docker.io
    - name: docker push
      shell: sudo docker push ekininaal/deneme-app:latest